### ISSUE TITLE
Dead link - https://devslop.co/Home/Privacy

### ISSUE THREAD

**Issue by yannpariseau** [DevSlop/DevSlop.co#10]
Hi DevSlop team.
When you click on the Learn More button from the second top menu, it brings you to https://devslop.co/Home/Privacy and you get a 404 error.

<img width="620" alt="learn more button" src="https://user-images.githubusercontent.com/32149096/50647039-99dbf500-0f45-11e9-9dab-6fb94fc2c139.png">

<img width="960" alt="2019-01-03" src="https://user-images.githubusercontent.com/32149096/50646518-4a48f980-0f44-11e9-9b01-41fc16f3208a.png">

**Comment by shehackspurple** [comment]
Same as last issue.  Closing.
