### ISSUE TITLE
Dead link - Accept button not working

### ISSUE THREAD

**Issue by yannpariseau** [DevSlop/DevSlop.co#11]
Hi DevSlop team,

When I click on the Accept button from the second top menu, nothing happens. Tried from Chrome, Firefox and Edge.

Relates to #10 

Regards,

Yann

**Comment by shehackspurple** [comment]
Hey Yann!

One of my teammates added the privacy notice, unaware that he needed to add it as a third party script in our HSTS security header.  It broke all the things.  

This website is offline now, so I'm going to close the issue.  Thanks for adding it!

Tanya
