### ISSUE TITLE
Confusing navbar with buttons

### ISSUE THREAD

**Issue by DanielRuf** [DevSlop/DevSlop.co#14]
The two top navbars are quite confusing UX wise.

![Bildschirmfoto 2019-04-09 um 08 08 31](https://user-images.githubusercontent.com/827205/55777058-0c0d2a00-5a9f-11e9-9471-bff79dad964d.png)

![Bildschirmfoto 2019-04-09 um 08 10 25](https://user-images.githubusercontent.com/827205/55777059-0c0d2a00-5a9f-11e9-8b01-4c9dd9902322.png)

**Comment by shehackspurple** [comment]
Yeah, one of my project teammates added a privacy notice, which used a third party script not listed in our HSTS security header, and it broken the nav.  I figured it before I took down the site, but since the site is down now....  Closing issue.  Thanks for pointing it out though!
