### ISSUE TITLE
Create unit tests....

### ISSUE THREAD

**Issue by shehackspurple** [DevSlop/DevSlop.co#4]

**Comment by Carl-Hugo** [comment]
Now that you have an empty-ish unit test project:

1. Do you have any specs or a list or do you know what you want to test (or just arbitrarily want to test everything)?
1. Do you want to run integration/functional tests as well (like in-memory HTTP queries)?
1. Do you want to run UI tests, load tests, etc. as well?

**Comment by shehackspurple** [comment]
This website is no longer in existence, closing issue.

Thanks for all of your supper Carl-Hugo, I really appreciate it!

**Comment by shehackspurple** [comment]
This website is no longer in existence, closing issue.
